# Generated by Django 3.1.1 on 2020-09-20 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('brand', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('picture1', models.ImageField(default='defaultproduct.png', upload_to='products_pics')),
                ('picture2', models.ImageField(default='defaultproduct.png', upload_to='products_pics')),
                ('picture3', models.ImageField(default='defaultproduct.png', upload_to='products_pics')),
                ('picture4', models.ImageField(default='defaultproduct.png', upload_to='products_pics')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpacifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=300)),
                ('ram', models.CharField(max_length=300)),
                ('camera', models.CharField(max_length=300)),
                ('battery', models.CharField(max_length=300)),
                ('display', models.CharField(max_length=300)),
                ('storage', models.CharField(max_length=300)),
                ('material', models.CharField(max_length=300)),
                ('os', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('ratingProduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('ratingUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspacifications'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('cartUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
