# Generated by Django 3.1.1 on 2020-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200922_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='defaultproduct.png', upload_to='products_offers')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
