# Generated by Django 3.1.1 on 2020-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='title',
            field=models.CharField(default='title', max_length=300),
        ),
        migrations.AlterField(
            model_name='offers',
            name='text',
            field=models.CharField(default='text', max_length=1000),
        ),
    ]
