# Generated by Django 3.1.1 on 2020-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartProduct',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartProduct',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
