# Generated by Django 3.1.1 on 2020-10-10 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20201010_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartProduct',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
