# Generated by Django 3.1.1 on 2020-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201010_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='productid',
            field=models.IntegerField(default=0),
        ),
    ]
