# Generated by Django 3.1.1 on 2020-10-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201021_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderProducts',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
